/**
 * Performance math — pure functions, no I/O.
 *
 * The whole point of this module is to give us an honest read on how the
 * portfolio is actually doing — TWR (so deposits/withdrawals don't fake the
 * return), CAGR (so we can compare to the 40% target), pillar attribution
 * (so we know which sleeves are pulling weight), and alpha vs SPY (so we
 * know whether the active strategy is earning its complexity).
 */

import type { CashFlowEvent, PortfolioSnapshot } from './storage';

// ─── Public types ────────────────────────────────────────────────────────────

export interface PeriodReturn {
  startDate: string;
  endDate: string;
  startAt: number;
  endAt: number;
  elapsedDays: number;
  startValue: number;
  endValue: number;
  netFlow: number;          // signed: + for inflow during period, - for outflow
  returnPct: number;        // Modified-Dietz return for the snapshot period
}

export interface TwrResult {
  twrPct: number;           // cumulative TWR over the full window, e.g. 0.12 = +12%
  cagrPct: number;          // annualized
  periods: PeriodReturn[];
  daysCovered: number;
  /** True when at least one period had insufficient data to compute. */
  hasGaps: boolean;
  /**
   * Dollar P/L over the same window, net of external cash flows:
   *   Σ (endValue − netFlow − startValue) across the measured periods.
   *
   * This is the money the portfolio actually made, with deposits and
   * withdrawals removed — the dollar counterpart to `twrPct`, computed from
   * the identical period set so the two always describe the same window.
   *
   * Note it is an arithmetic sum while `twrPct` chains geometrically, so
   * `gainDollars / startValue` will NOT exactly equal `twrPct` over a window
   * containing flows. That is expected: a percentage return and a dollar
   * total answer different questions once the capital base moves.
   */
  gainDollars: number;
  /**
   * Window summary, for showing the user what was actually measured.
   * Taken from the surviving periods, so these reflect the data the return
   * was computed from — not the raw first/last snapshot, which may have been
   * skipped as synthetic.
   */
  startValue: number;
  endValue: number;
  /** Signed net external flow over the window (+ deposits, − withdrawals). */
  netFlowTotal: number;
  startDate: string;
  endDate: string;
}

export interface PillarAttribution {
  pillar: string;
  /** Contribution to total portfolio return, in percentage points. */
  contributionPp: number;
  /** Pillar's own return % (independent of weight). */
  returnPct: number;
  avgWeightPct: number;
}

export interface AlphaVsSPY {
  portfolioReturnPct: number;
  spyReturnPct: number;
  alphaPp: number;          // portfolio − SPY, in percentage points
}

export interface Vs40Progress {
  actualCAGR: number;
  targetCAGR: number;       // always 0.40
  gapPp: number;            // actualCAGR − targetCAGR, in percentage points (negative = behind)
  paceLabel: 'ahead' | 'on-pace' | 'behind';
  /** What return-rate would close the gap by year-end? */
  requiredForwardCAGR: number | null;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function toDayKey(ts: number): string {
  return new Date(ts).toISOString().slice(0, 10);
}

/**
 * Sum *external* cash-flow events in (startDate, endDate]. Only deposits,
 * withdrawals, and inter-account journals are netted out of return — those
 * are money crossing the account boundary that shouldn't be counted as
 * performance.
 *
 * Dividends, interest credits, margin interest, and fees are NOT external
 * flows — they're income/expenses generated by holding the portfolio, and
 * belong in the return. Keeping them out of `netFlow` lets them remain in the
 * period's investment gain or loss.
 *
 * The flow is signed: inflows positive, outflows negative — to subtract from
 * end value.
 */
const EXTERNAL_FLOW_KINDS: ReadonlySet<CashFlowEvent['kind']> = new Set([
  'deposit',
  'withdrawal',
  'journal',
]);

function exactFlowTimestamp(flow: CashFlowEvent): number | null {
  const exact = flow.occurredAt ? Date.parse(flow.occurredAt) : NaN;
  return Number.isFinite(exact) ? exact : null;
}

function flowsInPeriod(
  flows: CashFlowEvent[],
  startAt: number,
  endAt: number,
): { netFlow: number; weightedFlow: number } {
  let net = 0;
  let weighted = 0;
  const duration = endAt - startAt;
  const startDay = toDayKey(startAt);
  const endDay = toDayKey(endAt);
  for (const f of flows) {
    if (!EXTERNAL_FLOW_KINDS.has(f.kind)) continue;
    const exact = exactFlowTimestamp(f);
    // Broker records captured before `occurredAt` shipped, plus manual entries,
    // only identify a calendar day. Assign those to the snapshot period ending
    // on that day. Treating them as 23:59 put them *after* a daytime snapshot,
    // briefly counted the deposited balance as performance, and could wildly
    // inflate the geometrically chained return.
    if (exact == null) {
      if (f.date <= startDay || f.date > endDay) continue;
    } else if (exact <= startAt || exact > endAt) {
      continue;
    }
    const signed = f.direction === 'in' ? f.amount : -f.amount;
    net += signed;
    // Exact events use Modified Dietz timing. With no timestamp, use the
    // established end-of-period convention (zero denominator weight).
    if (exact != null) weighted += signed * ((endAt - exact) / duration);
  }
  return { netFlow: net, weightedFlow: weighted };
}

// ─── TWR ─────────────────────────────────────────────────────────────────────

/**
 * Time-Weighted Return over a series of snapshots.
 *
 * Each adjacent snapshot period uses Modified Dietz. Exact broker timestamps
 * weight external cash by how long it was invested; legacy date-only flows are
 * treated as end-of-period. Period returns are then geometrically chained.
 *
 * We use `equity` (net liquidation value: positions + cash − margin debt) rather
 * than `totalValue` (positions only). This matters for two reasons:
 *  1. Cash dividends land in cash, not in position market value. Using equity
 *     captures them as return.
 *  2. On ex-dividend day a position drops by the dividend amount. If we used
 *     positions-only, that drop would show up as a real loss; using equity
 *     means the offsetting cash credit cancels it out.
 *
 * Periods are chained geometrically and annualized to CAGR using actual
 * elapsed calendar days.
 */
export function computeTWR(snapshots: PortfolioSnapshot[], cashFlows: CashFlowEvent[]): TwrResult | null {
  if (snapshots.length < 2) return null;

  // Sort ascending by savedAt (defensive — store usually already sorted)
  const sorted = [...snapshots].sort((a, b) => a.savedAt - b.savedAt);
  const periods: PeriodReturn[] = [];
  let hasGaps = false;

  for (let i = 1; i < sorted.length; i++) {
    const A = sorted[i - 1];
    const B = sorted[i];
    // Null equity = synthetic (reconstructed) snapshot — no real equity data.
    // Skip these periods rather than compute returns off fabricated numbers.
    if (!A.equity || A.equity <= 0 || B.equity == null || B.equity <= 0) { hasGaps = true; continue; }

    const startDate = toDayKey(A.savedAt);
    const endDate   = toDayKey(B.savedAt);
    const elapsedDays = (B.savedAt - A.savedAt) / (24 * 60 * 60 * 1000);
    if (elapsedDays <= 0) { hasGaps = true; continue; }
    const { netFlow, weightedFlow } = flowsInPeriod(cashFlows, A.savedAt, B.savedAt);
    const denominator = A.equity + weightedFlow;
    if (denominator <= 0) { hasGaps = true; continue; }
    const ret = (B.equity - A.equity - netFlow) / denominator;

    periods.push({
      startDate, endDate,
      startAt: A.savedAt,
      endAt: B.savedAt,
      elapsedDays,
      startValue: A.equity,
      endValue:   B.equity,
      netFlow,
      returnPct:  ret,
    });
  }

  if (periods.length === 0) return null;

  const twr = periods.reduce((acc, p) => acc * (1 + p.returnPct), 1) - 1;
  // Sum only periods that actually participated. This avoids annualizing over
  // skipped invalid spans as though they earned a zero return.
  const days = periods.reduce((sum, period) => sum + period.elapsedDays, 0);
  const cagr = days > 0 && twr > -1 ? Math.pow(1 + twr, 365 / days) - 1 : -1;
  // Dollar P/L over the same periods, with external flows removed. Built from
  // `periods` rather than first/last equity so skipped (gappy) periods are
  // excluded from the dollar figure exactly as they are from the percentage.
  const gainDollars = periods.reduce((acc, p) => acc + (p.endValue - p.netFlow - p.startValue), 0);
  const netFlowTotal = periods.reduce((acc, p) => acc + p.netFlow, 0);
  const first = periods[0];
  const last  = periods[periods.length - 1];

  return {
    twrPct: twr, cagrPct: cagr, periods, daysCovered: days, hasGaps, gainDollars,
    startValue: first.startValue,
    endValue:   last.endValue,
    netFlowTotal,
    startDate:  first.startDate,
    endDate:    last.endDate,
  };
}

// ─── Pillar attribution ──────────────────────────────────────────────────────

/**
 * Per-pillar contribution to total return.
 *
 * For each adjacent pair, the pillar's return for the period is computed
 * directly from its dollar value — we DO NOT subtract intra-period trades
 * here because trades just shift dollars between pillars (zero-sum), they
 * don't add or subtract from total portfolio value. The TWR-style flow
 * adjustment lives at the *portfolio* level.
 *
 * Within a period, each pillar's contribution to total return =
 *   pillarStartWeight × pillarReturn
 * Summed across periods (weighted by period length), this gives a
 * cumulative attribution that approximately reconciles with the total TWR.
 */
export function computePillarAttribution(snapshots: PortfolioSnapshot[]): PillarAttribution[] {
  if (snapshots.length < 2) return [];
  const sorted = [...snapshots].sort((a, b) => a.savedAt - b.savedAt);

  const acc = new Map<string, { contribution: number; weightSum: number; weightCount: number; geomReturn: number }>();

  for (let i = 1; i < sorted.length; i++) {
    const A = sorted[i - 1];
    const B = sorted[i];
    if (!A.totalValue || !B.totalValue) continue;

    for (const startPillar of A.pillarSummary) {
      const endPillar = B.pillarSummary.find((p) => p.pillar === startPillar.pillar);
      if (!endPillar || startPillar.totalValue <= 0) continue;

      const pillarReturn = endPillar.totalValue / startPillar.totalValue - 1;
      const weight       = startPillar.totalValue / A.totalValue;
      const contribution = weight * pillarReturn;

      const cur = acc.get(startPillar.pillar) ?? { contribution: 0, weightSum: 0, weightCount: 0, geomReturn: 1 };
      cur.contribution += contribution;
      cur.weightSum    += startPillar.portfolioPercent;
      cur.weightCount  += 1;
      cur.geomReturn   *= (1 + pillarReturn);
      acc.set(startPillar.pillar, cur);
    }
  }

  return Array.from(acc.entries())
    .map(([pillar, v]) => ({
      pillar,
      contributionPp: v.contribution * 100,
      returnPct:      (v.geomReturn - 1) * 100,
      avgWeightPct:   v.weightCount > 0 ? v.weightSum / v.weightCount : 0,
    }))
    .sort((a, b) => b.contributionPp - a.contributionPp);
}

// ─── SPY benchmark ───────────────────────────────────────────────────────────

/**
 * Cumulative return of the portfolio vs SPY over the snapshot window.
 * Requires snapshots to carry `spyClose`. Snapshots missing the field are
 * skipped on both sides so the comparison is apples-to-apples.
 */
export function computeAlphaVsSPY(snapshots: PortfolioSnapshot[], cashFlows: CashFlowEvent[]): AlphaVsSPY | null {
  const withSpy = snapshots
    .filter((s) => typeof s.spyClose === 'number' && s.spyClose > 0)
    .sort((a, b) => a.savedAt - b.savedAt);
  if (withSpy.length < 2) return null;

  const portfolioTwr = computeTWR(withSpy, cashFlows);
  if (!portfolioTwr) return null;

  const first = withSpy[0].spyClose!;
  const last  = withSpy[withSpy.length - 1].spyClose!;
  const spyReturn = last / first - 1;

  return {
    portfolioReturnPct: portfolioTwr.twrPct * 100,
    spyReturnPct:       spyReturn * 100,
    alphaPp:            (portfolioTwr.twrPct - spyReturn) * 100,
  };
}

// ─── 40% target progress ─────────────────────────────────────────────────────

/**
 * How are we tracking against the 40% annual CAGR target?
 *
 * `actualCAGR` should be the annualized return computed by `computeTWR`.
 * `daysSinceStart` is the elapsed window we're measuring over (used to
 * back out what forward CAGR would be needed to hit 40% by the
 * one-year mark from the start date).
 */
export function computeProgressVs40(actualCAGR: number, daysSinceStart: number): Vs40Progress {
  const target = 0.40;
  const gapPp  = (actualCAGR - target) * 100;

  let paceLabel: 'ahead' | 'on-pace' | 'behind';
  if (gapPp >= 2)       paceLabel = 'ahead';
  else if (gapPp >= -2) paceLabel = 'on-pace';
  else                  paceLabel = 'behind';

  let requiredForwardCAGR: number | null = null;
  if (daysSinceStart > 0 && daysSinceStart < 365) {
    // Cumulative return so far at the actualCAGR rate
    const cumReturnSoFar = Math.pow(1 + actualCAGR, daysSinceStart / 365) - 1;
    const remainingDays  = 365 - daysSinceStart;
    // Required cumulative growth over remaining year to reach 1+target overall
    const requiredFactor = (1 + target) / (1 + cumReturnSoFar);
    if (requiredFactor > 0) {
      requiredForwardCAGR = Math.pow(requiredFactor, 365 / remainingDays) - 1;
    }
  }

  return { actualCAGR, targetCAGR: target, gapPp, paceLabel, requiredForwardCAGR };
}
